### ISSUE TITLE
BomberAction state machine

### ISSUE THREAD

**Issue by fsantanna** [Tkachov/ceu_pingus#5]
There's a state machine that is clearly a sequence in `BomberAction` (using `get_current_frame() > *`):

```
<loop-for-<=9>
<loop-for->9-and-no-sound>
<loop-for->12-and-not-thrown>
<loop-for->13-and-not-exploded>
```

(I'm writing all those as issues to provide you very specific feedback. Please, do not try to discuss/address them all at once, I know there's a lengthy process going on. They can stay here for a while, until you want to check them...)

**Comment by Tkachov** [comment]
I just don't know how to translate that to something closer to Ceu approach. What do you mean by `loop-for`? There is a special construct or something?

(Sure.)

**Comment by fsantanna** [comment]
No.
It means that they are 4 different behaviors that happen in sequence and you don't need state variables for that, just use a sequence:

```
// 1st behavior:
every FRAME do
    <do-whatever>
    break;  // condition to terminate this behavior
end
// 2nd behavior
every FRAME do
    <do-whatever>
    break;  // condition to terminate this behavior
end
// and so on...
```

**Comment by Tkachov** [comment]
OK. But still we will test those conditions to break from such `every` loops, right?

**Comment by fsantanna** [comment]
Sure, but the state variables should go away (`sound_played`, etc).
